---
settings:
  name: NetApp NFS Plug-in for VMware VAAI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,zh-cn,zh-tw,ko-kr,de-de
sidebar:
  entries:
  - title: Plug-in NetApp NFS pour les documents VMware VAAI
    url: "/index.html"
  - title: Notes de version
    url: "/releasenotes.html"
  - title: Installation et configuration
    entries:
    - title: Installation du plug-in NetApp NFS pour VMware VAAI
      url: "/task-install-netapp-nfs-plugin-for-vmware-vaai.html"
    - title: Configurer les export policy pour ONTAP afin de permettre VAAI sur NFS
      url: "/task-configure-export-policies-for-clustered-data-ontap-to-allow-vaai-over-nfs.html"
  - title: Mentions légales
    url: "/reference-legal-notices.html"
